#服务器端口
server:
  port: 10515
  servlet:
    context-path: /worktool

spring:
  datasource:
    username: deployop
    password: 123456
    url: jdbc:mysql://1.1.1.1:16665/cloudpay?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver























